# Generated by Django 5.2.4 on 2025-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
